name: Deploy to Firebase

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install root dependencies
        run: npm install

      - name: Install frontend dependencies
        run: npm install --prefix frontend

      - name: Install functions dependencies
        run: npm install --prefix backend/functions

      - name: Build frontend
        run: npm run build --workspace=frontend

      - name: List files in the root directory
        run: ls -la

      - name: Deploy to Firebase
        uses: w9jds/firebase-action@master
        with:
          args: deploy --only hosting,functions --project trippingly-on-the-tongue
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}